return {
    ["Ammo"] = 40,
    ["DamageFallOf"] = 1,
    ["ShootRate"] = 800,
    ["IgnoreProtection"] = true,
    ["EnableZeroing"] = true,
    ["MinRecoilPower"] = 0.5,
    ["Zoom"] = 58,
    ["MaxRecoilPower"] = 1.5,
    ["SightAtt"] = "",
    ["BulletPenetration"] = 70,
    ["CanCheckMag"] = true,
    ["MuzzleVelocity"] = 1500,
    ["CanBreachDoor"] = false,
    ["AmmoInGun"] = 36,
    ["camRecoil"] = {
        ["camRecoilUp"] = {
            [1] = 2,
            [2] = 3
        },
        ["camRecoilRight"] = {
            [1] = 1,
            [2] = 3
        },
        ["camRecoilLeft"] = {
            [1] = 1,
            [2] = 3
        },
        ["camRecoilTilt"] = {
            [1] = 2,
            [2] = 4
        }
    },
    ["gunName"] = "AR-15",
    ["HeadDamage"] = {
        [1] = 135,
        [2] = 135
    },
    ["Zoom2"] = 48,
    ["MagCount"] = true,
    ["InfraRed"] = false,
    ["AimInaccuracyStepAmount"] = 0.75,
    ["CurrentZero"] = 0,
    ["RainbowMode"] = false,
    ["CrosshairOffset"] = 10,
    ["AimSpreadReduction"] = 1,
    ["ShootType"] = 3,
    ["FlashChance"] = 4,
    ["Bullets"] = 1,
    ["EnableHUD"] = true,
    ["SlideEx"] = CFrame.new(0, 0, -0.4000000059604645, 1, 0, 0, 0, 1, 0, 0, 0, 1),
    ["Tracer"] = true,
    ["LimbDamage"] = {
        [1] = 20,
        [2] = 30
    },
    ["MaxStoredAmmo"] = 210000,
    ["UnderBarrelAtt"] = "",
    ["TracerColor"] = Color3.new(1, 1, 1),
    ["TracerEveryXShots"] = 3,
    ["CenterDot"] = false,
    ["CanBreak"] = false,
    ["TorsoDamage"] = {
        [1] = 35,
        [2] = 40
    },
    ["ShellInsert"] = false,
    ["MinDamage"] = 5,
    ["gunRecoil"] = {
        ["gunRecoilTilt"] = {
            [1] = 8,
            [2] = 10
        },
        ["gunRecoilUp"] = {
            [1] = 10,
            [2] = 15
        },
        ["gunRecoilLeft"] = {
            [1] = 8,
            [2] = 10
        },
        ["gunRecoilRight"] = {
            [1] = 8,
            [2] = 10
        }
    },
    ["BurstShot"] = 3,
    ["RecoilPowerStepAmount"] = 0.1,
    ["Type"] = "Gun",
    ["MaxSpread"] = 5,
    ["CrossHair"] = false,
    ["FireModes"] = {
        ["Auto"] = true,
        ["ChangeFiremode"] = true,
        ["Burst"] = false,
        ["Semi"] = true
    },
    ["SlideLock"] = true,
    ["BarrelAtt"] = "",
    ["OtherAtt"] = "",
    ["BulletType"] = "5.56x45mm",
    ["AimRecoilReduction"] = 4,
    ["IncludeChamberedBullet"] = true,
    ["canAim"] = true,
    ["MaxZero"] = 500,
    ["AimInaccuracyDecrease"] = 0.25,
    ["adsTime"] = 0.8,
    ["BulletFlare"] = false,
    ["StoredAmmo"] = 210000,
    ["MinSpread"] = 0,
    ["WalkMult"] = 0,
    ["ZeroIncrement"] = 50,
    ["BulletDrop"] = 0,
    ["Jammed"] = false,
    ["RandomTracer"] = {
        ["Enabled"] = false,
        ["Chance"] = 25
    }
}
